-- EchoReach Supabase PostgreSQL Schema Script
-- Can be executed in Supabase SQL Editor or tables will be auto-generated by SQLAlchemy Base.metadata.create_all

CREATE TABLE IF NOT EXISTS leads (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    title VARCHAR(100) NOT NULL,
    company VARCHAR(100) NOT NULL,
    email VARCHAR(120) UNIQUE NOT NULL,
    linkedin_url VARCHAR(255),
    stage VARCHAR(50) DEFAULT 'New',
    current_touch_number INT DEFAULT 1,
    status VARCHAR(50) DEFAULT 'Active',
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc')
);

CREATE TABLE IF NOT EXISTS research_facts (
    id SERIAL PRIMARY KEY,
    lead_id INT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
    fact_type VARCHAR(50) NOT NULL,
    content TEXT NOT NULL,
    source VARCHAR(255),
    kept_reason TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc')
);

CREATE TABLE IF NOT EXISTS touches (
    id SERIAL PRIMARY KEY,
    lead_id INT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
    touch_number INT NOT NULL,
    channel VARCHAR(50) DEFAULT 'email',
    subject VARCHAR(255),
    body TEXT NOT NULL,
    status VARCHAR(50) DEFAULT 'pending_approval',
    sent_at TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc')
);

CREATE TABLE IF NOT EXISTS decision_log (
    id SERIAL PRIMARY KEY,
    lead_id INT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
    agent_name VARCHAR(100) NOT NULL,
    input_summary TEXT,
    reasoning TEXT NOT NULL,
    output_summary TEXT,
    timestamp TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc')
);

CREATE TABLE IF NOT EXISTS suppression_list (
    id SERIAL PRIMARY KEY,
    email VARCHAR(120) UNIQUE,
    domain VARCHAR(100),
    reason VARCHAR(255) DEFAULT 'User requested opt-out',
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc')
);

CREATE TABLE IF NOT EXISTS simulated_inbox (
    id SERIAL PRIMARY KEY,
    lead_id INT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
    touch_id INT NOT NULL REFERENCES touches(id) ON DELETE CASCADE,
    channel VARCHAR(50) DEFAULT 'email',
    subject VARCHAR(255),
    body TEXT NOT NULL,
    sent_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
    status VARCHAR(50) DEFAULT 'Delivered'
);

CREATE TABLE IF NOT EXISTS replies (
    id SERIAL PRIMARY KEY,
    lead_id INT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
    touch_id INT REFERENCES touches(id),
    persona_type VARCHAR(50) NOT NULL,
    raw_text TEXT NOT NULL,
    classification VARCHAR(50) NOT NULL,
    confidence FLOAT DEFAULT 0.95,
    reasoning TEXT,
    is_corrected INT DEFAULT 0,
    corrected_classification VARCHAR(50),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc')
);

CREATE TABLE IF NOT EXISTS classifier_feedback (
    id SERIAL PRIMARY KEY,
    reply_id INT REFERENCES replies(id),
    raw_text TEXT NOT NULL,
    predicted_class VARCHAR(50) NOT NULL,
    corrected_class VARCHAR(50) NOT NULL,
    notes TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc')
);

CREATE TABLE IF NOT EXISTS daily_send_counter (
    id SERIAL PRIMARY KEY,
    date_str VARCHAR(20) UNIQUE NOT NULL,
    send_count INT DEFAULT 0,
    daily_cap INT DEFAULT 50
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_leads_stage ON leads(stage);
CREATE INDEX IF NOT EXISTS idx_decision_log_agent ON decision_log(agent_name);
CREATE INDEX IF NOT EXISTS idx_touches_status ON touches(status);
